New Test case

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,11 +31,32 @@ jobs:
       - name: Test Ofelia (with config mount)
         run: |
           # Create a dummy ofelia config file for testing
-          echo "[job-exec \"example\"]\nschedule = \"@every 10s\"\ncommand = \"/bin/echo Hello Ofelia\"" > ofelia.ini
+          echo '[job-exec "example"]' > ofelia.ini
+          echo 'schedule = "@every 10s"' >> ofelia.ini
+          echo 'command = "/bin/echo Hello Ofelia"' >> ofelia.ini
+          
+          # Run the container in detached mode
           docker run --name cronned-rclone \
             -v /var/run/docker.sock:/var/run/docker.sock:ro \
             -v $PWD/ofelia.ini:/config/ofelia.ini \
-            ${{ env.DOCKER_IMAGE_TAG }}
+            -d ${{ env.DOCKER_IMAGE_TAG }}
+
+          # Wait for 10 seconds
+          sleep 10
+
+          # Check logs for "Hello Ofelia"
+          if docker logs cronned-rclone | grep -q "Hello Ofelia"; then
+            echo "Output found: Hello Ofelia"
+          else
+            echo "Expected output not found"
+            docker logs cronned-rclone  # Print logs for debugging
+            exit 1  # Fail the job
+          fi
+
+          # Stop and remove the container
+          docker stop cronned-rclone
+          docker rm cronned-rclon
+
 
       - name: Test Rclone Version
         run: |
